package com.hermes.android.ui.theme

import androidx.compose.ui.graphics.Color

// ── Hermes2 Default palette — deep agent console + cyan/violet accents ──

// Light theme
val md_light_primary = Color(0xFF5B4BDB)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFE5DEFF)
val md_light_onPrimaryContainer = Color(0xFF17005C)
val md_light_secondary = Color(0xFF006A78)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFA8EEFF)
val md_light_onSecondaryContainer = Color(0xFF001F26)
val md_light_tertiary = Color(0xFF256A4F)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFA9F2CF)
val md_light_onTertiaryContainer = Color(0xFF002115)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFF8FAFF)
val md_light_onBackground = Color(0xFF171A23)
val md_light_surface = Color(0xFFFFFFFF)
val md_light_onSurface = Color(0xFF171A23)
val md_light_surfaceVariant = Color(0xFFE2E5F2)
val md_light_onSurfaceVariant = Color(0xFF444754)
val md_light_outline = Color(0xFF747785)
val md_light_outlineVariant = Color(0xFFC4C6D4)

// Dark theme
val md_dark_primary = Color(0xFF9B8CFF)
val md_dark_onPrimary = Color(0xFF24008A)
val md_dark_primaryContainer = Color(0xFF3F2CB5)
val md_dark_onPrimaryContainer = Color(0xFFE8DDFF)
val md_dark_secondary = Color(0xFF67D9F2)
val md_dark_onSecondary = Color(0xFF003640)
val md_dark_secondaryContainer = Color(0xFF004E5C)
val md_dark_onSecondaryContainer = Color(0xFFB6EBFF)
val md_dark_tertiary = Color(0xFF7EDDB3)
val md_dark_onTertiary = Color(0xFF003823)
val md_dark_tertiaryContainer = Color(0xFF005137)
val md_dark_onTertiaryContainer = Color(0xFF9AF8CD)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF080D16)
val md_dark_onBackground = Color(0xFFE4E8F4)
val md_dark_surface = Color(0xFF0D1420)
val md_dark_onSurface = Color(0xFFE4E8F4)
val md_dark_surfaceVariant = Color(0xFF202938)
val md_dark_onSurfaceVariant = Color(0xFFC3CAD8)
val md_dark_outline = Color(0xFF8D95A6)
val md_dark_outlineVariant = Color(0xFF3D4658)

// ── آبی چشم (Blue Eye) — طراحی شده برای راحتی چشم در استفاده طولانی ──
// کنتراست کم، آبی ملایم، سفید گرم (نه سفید خالص)

val blue_light_primary = Color(0xFF3D7BAF)
val blue_light_onPrimary = Color(0xFFFFFFFF)
val blue_light_primaryContainer = Color(0xFFD6E8F7)
val blue_light_onPrimaryContainer = Color(0xFF0A2940)
val blue_light_secondary = Color(0xFF4A7C8F)
val blue_light_onSecondary = Color(0xFFFFFFFF)
val blue_light_secondaryContainer = Color(0xFFD0E6EE)
val blue_light_onSecondaryContainer = Color(0xFF07272F)
val blue_light_tertiary = Color(0xFF5A7A6D)
val blue_light_onTertiary = Color(0xFFFFFFFF)
val blue_light_tertiaryContainer = Color(0xFFD4EDE2)
val blue_light_onTertiaryContainer = Color(0xFF112820)
val blue_light_error = Color(0xFFBA1A1A)
val blue_light_onError = Color(0xFFFFFFFF)
val blue_light_errorContainer = Color(0xFFFFDAD6)
val blue_light_onErrorContainer = Color(0xFF410002)
val blue_light_background = Color(0xFFF4F7FA)
val blue_light_onBackground = Color(0xFF1A2836)
val blue_light_surface = Color(0xFFFAFCFE)
val blue_light_onSurface = Color(0xFF1A2836)
val blue_light_surfaceVariant = Color(0xFFDDE5EC)
val blue_light_onSurfaceVariant = Color(0xFF3D4A54)
val blue_light_outline = Color(0xFF6B7A85)
val blue_light_outlineVariant = Color(0xFFB8C5CE)

val blue_dark_primary = Color(0xFF7EB8E0)
val blue_dark_onPrimary = Color(0xFF0A2940)
val blue_dark_primaryContainer = Color(0xFF1E4060)
val blue_dark_onPrimaryContainer = Color(0xFFD6E8F7)
val blue_dark_secondary = Color(0xFF8DC0D0)
val blue_dark_onSecondary = Color(0xFF07272F)
val blue_dark_secondaryContainer = Color(0xFF1A3E4A)
val blue_dark_onSecondaryContainer = Color(0xFFD0E6EE)
val blue_dark_tertiary = Color(0xFF8BB8A8)
val blue_dark_onTertiary = Color(0xFF112820)
val blue_dark_tertiaryContainer = Color(0xFF1E3F34)
val blue_dark_onTertiaryContainer = Color(0xFFD4EDE2)
val blue_dark_error = Color(0xFFFFB4AB)
val blue_dark_onError = Color(0xFF690005)
val blue_dark_errorContainer = Color(0xFF93000A)
val blue_dark_onErrorContainer = Color(0xFFFFDAD6)
val blue_dark_background = Color(0xFF0F1923)
val blue_dark_onBackground = Color(0xFFD8E4EC)
val blue_dark_surface = Color(0xFF152231)
val blue_dark_onSurface = Color(0xFFD8E4EC)
val blue_dark_surfaceVariant = Color(0xFF1E2D3D)
val blue_dark_onSurfaceVariant = Color(0xFFB0BEC8)
val blue_dark_outline = Color(0xFF5A7085)
val blue_dark_outlineVariant = Color(0xFF2E3E4E)

// ── موکا (Mocha) — تم گرم و ملایم، جایگزین Claude ──
// قهوه‌ای نرم و کرم‌رنگ، مناسب برای مطالعه طولانی

val claude_light_primary = Color(0xFF7D6B52)
val claude_light_onPrimary = Color(0xFFFFFFFF)
val claude_light_primaryContainer = Color(0xFFEDE3D6)
val claude_light_onPrimaryContainer = Color(0xFF2C2012)
val claude_light_secondary = Color(0xFF6B7B6A)
val claude_light_onSecondary = Color(0xFFFFFFFF)
val claude_light_secondaryContainer = Color(0xFFDDE8DC)
val claude_light_onSecondaryContainer = Color(0xFF1A2618)
val claude_light_tertiary = Color(0xFF7A6E60)
val claude_light_onTertiary = Color(0xFFFFFFFF)
val claude_light_tertiaryContainer = Color(0xFFEAE0D4)
val claude_light_onTertiaryContainer = Color(0xFF2A2218)
val claude_light_error = Color(0xFFBA1A1A)
val claude_light_onError = Color(0xFFFFFFFF)
val claude_light_errorContainer = Color(0xFFFFDAD6)
val claude_light_onErrorContainer = Color(0xFF410002)
val claude_light_background = Color(0xFFFAF8F5)
val claude_light_onBackground = Color(0xFF1E1C19)
val claude_light_surface = Color(0xFFFFFDF9)
val claude_light_onSurface = Color(0xFF1E1C19)
val claude_light_surfaceVariant = Color(0xFFEDE7DF)
val claude_light_onSurfaceVariant = Color(0xFF4A453E)
val claude_light_outline = Color(0xFF7A756D)
val claude_light_outlineVariant = Color(0xFFCCC5BC)

val claude_dark_primary = Color(0xFFC4A882)
val claude_dark_onPrimary = Color(0xFF2C2012)
val claude_dark_primaryContainer = Color(0xFF4A3D2C)
val claude_dark_onPrimaryContainer = Color(0xFFEDE3D6)
val claude_dark_secondary = Color(0xFFA4B5A3)
val claude_dark_onSecondary = Color(0xFF1A2618)
val claude_dark_secondaryContainer = Color(0xFF2E3E2C)
val claude_dark_onSecondaryContainer = Color(0xFFDDE8DC)
val claude_dark_tertiary = Color(0xFFBBAFA0)
val claude_dark_onTertiary = Color(0xFF2A2218)
val claude_dark_tertiaryContainer = Color(0xFF453C30)
val claude_dark_onTertiaryContainer = Color(0xFFEAE0D4)
val claude_dark_error = Color(0xFFFFB4AB)
val claude_dark_onError = Color(0xFF690005)
val claude_dark_errorContainer = Color(0xFF93000A)
val claude_dark_onErrorContainer = Color(0xFFFFDAD6)
val claude_dark_background = Color(0xFF1A1614)
val claude_dark_onBackground = Color(0xFFE8DFD5)
val claude_dark_surface = Color(0xFF211E1B)
val claude_dark_onSurface = Color(0xFFE8DFD5)
val claude_dark_surfaceVariant = Color(0xFF332E28)
val claude_dark_onSurfaceVariant = Color(0xFFC4BAB0)
val claude_dark_outline = Color(0xFF8A8078)
val claude_dark_outlineVariant = Color(0xFF3E382F)
