package com.hermes.android.runtime.termux

import android.content.Context
import dagger.hilt.android.qualifiers.ApplicationContext
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Generates the bash install command for Termux using install.sh's native
 * --stage and --json API (Fix S2F02, S2F04).
 *
 * install.sh supports:
 *   --manifest  → outputs JSON stage list
 *   --stage NAME → runs one stage
 *   --json       → outputs JSON result for the stage
 *
 * The generated script:
 * 1. Downloads install.sh
 * 2. Runs --manifest to get the stage list
 * 3. Runs each stage with --stage NAME --json
 * 4. Reports progress via am broadcast after each stage
 * 5. Verifies hermes --version and hermes doctor (Fix S2F05, S2F06)
 * 6. Reports Python version (Fix S2F01)
 *
 * Reference: ADR-007, scripts/install.sh:124-128, 271, 282-292
 */
@Singleton
class TermuxInstaller @Inject constructor(
    @ApplicationContext private val context: Context,
) {

    enum class BroadcastAction(val action: String) {
        PROGRESS("com.hermes.android.INSTALL_PROGRESS"),
        COMPLETE("com.hermes.android.INSTALL_COMPLETE"),
        ERROR("com.hermes.android.INSTALL_ERROR"),
    }

    /**
     * The pure bash script body that performs the Hermes install inside Termux.
     *
     * This is the canonical install script. It is sent to Termux via
     * [TermuxCommandExecutor.executeBackgroundScript] — NOT via copy/paste.
     * Kept as a separate method so the script can be unit-tested and reused
     * by both the automated path and (as a fallback) the legacy copy/paste
     * instructions screen.
     */
    fun generateInstallScript(): String {
        val receiver = context.packageName
        return buildString {
            appendLine("# Hermes Agent — Android install script")
            appendLine("# Generated by Hermes2 app. Executed automatically via RUN_COMMAND.")
            appendLine("# Uses install.sh native --stage --json API")
            appendLine("set -e")
            appendLine("set -o pipefail")
            appendLine()
            appendLine("RECEIVER=\"$receiver\"")
            appendLine("PROGRESS_ACTION=\"${BroadcastAction.PROGRESS.action}\"")
            appendLine("COMPLETE_ACTION=\"${BroadcastAction.COMPLETE.action}\"")
            appendLine("ERROR_ACTION=\"${BroadcastAction.ERROR.action}\"")
            appendLine("INSTALL_URL=\"https://hermes-agent.nousresearch.com/install.sh\"")
            appendLine("REPO_DIR=\"\$HOME/.hermes/hermes-agent\"")
            appendLine()
            appendLine("report_progress() {")
            appendLine("    local stage=\"\$1\" message=\"\$2\" percent=\"\$3\"")
            appendLine("    am broadcast -p \"\$RECEIVER\" -a \"\$PROGRESS_ACTION\" \\")
            appendLine("        --es stage \"\$stage\" \\")
            appendLine("        --es message \"\$message\" \\")
            appendLine("        --ei percent \"\$percent\" >/dev/null 2>&1 || true")
            appendLine("}")
            appendLine()
            appendLine("report_complete() {")
            appendLine("    am broadcast -p \"\$RECEIVER\" -a \"\$COMPLETE_ACTION\" >/dev/null 2>&1 || true")
            appendLine("}")
            appendLine()
            appendLine("report_error() {")
            appendLine("    local message=\"\$1\"")
            appendLine("    am broadcast -p \"\$RECEIVER\" -a \"\$ERROR_ACTION\" --es message \"\$message\" >/dev/null 2>&1 || true")
            appendLine("}")
            appendLine()
            appendLine("trap 'report_error \"Install failed at stage: \$STAGE\"' ERR")
            appendLine()
            appendLine("# Download install.sh")
            appendLine("STAGE=\"repository\"")
            appendLine("report_progress \"\$STAGE\" \"Downloading Hermes Agent installer...\" 5")
            appendLine("mkdir -p \"\$HOME/.hermes/logs\"")
            appendLine("# Bootstrap only what is needed to download the official installer.")
            appendLine("# Full prerequisites are installed by install.sh's prerequisites stage.")
            appendLine("if ! command -v curl >/dev/null 2>&1; then")
            appendLine("    pkg update -y 2>&1 | tee -a \"\$HOME/.hermes/logs/install.log\" || true")
            appendLine("    pkg install -y curl ca-certificates 2>&1 | tee -a \"\$HOME/.hermes/logs/install.log\"")
            appendLine("fi")
            appendLine("# Recover from failed installs that left a non-git repo path behind")
            appendLine("if [ -e \"\$REPO_DIR\" ] && [ ! -d \"\$REPO_DIR/.git\" ]; then")
            appendLine("    BROKEN_REPO_DIR=\"\$REPO_DIR.broken-\$(date +%Y%m%d-%H%M%S)\"")
            appendLine("    report_progress \"repository\" \"Moving non-git Hermes repo aside: \$BROKEN_REPO_DIR\" 6")
            appendLine("    echo \"Moving non-git Hermes repo aside: \$REPO_DIR -> \$BROKEN_REPO_DIR\" | tee -a \"\$HOME/.hermes/logs/install.log\"")
            appendLine("    mv \"\$REPO_DIR\" \"\$BROKEN_REPO_DIR\"")
            appendLine("fi")
            appendLine("curl -fsSL \"\$INSTALL_URL\" -o \"\$HOME/hermes_install.sh\" 2>&1 | tee \"\$HOME/.hermes/logs/install.log\"")
            appendLine("chmod +x \"\$HOME/hermes_install.sh\"")
            appendLine()
            appendLine("prepare_android_rust_env() {")
            appendLine("    if [ -z \"\${ANDROID_API_LEVEL:-}\" ]; then")
            appendLine("        ANDROID_API_LEVEL=\$(getprop ro.build.version.sdk 2>/dev/null || true)")
            appendLine("        [ -n \"\$ANDROID_API_LEVEL\" ] || ANDROID_API_LEVEL=24")
            appendLine("        export ANDROID_API_LEVEL")
            appendLine("    fi")
            appendLine("    # maturin/jiter builds on Termux often need the native Rust target")
            appendLine("    # spelled out explicitly, otherwise build isolation can fail while")
            appendLine("    # installing jiter's Rust build dependencies.")
            appendLine("    if command -v rustc >/dev/null 2>&1; then")
            appendLine("        CARGO_BUILD_TARGET=\$(rustc -Vv | awk '/^host:/ {print \$2; exit}')")
            appendLine("        [ -n \"\$CARGO_BUILD_TARGET\" ] && export CARGO_BUILD_TARGET")
            appendLine("    fi")
            appendLine("}")
            appendLine()
            appendLine("ensure_termux_rust_build_prereqs() {")
            appendLine("    # Upstream install.sh installs most of these. binutils-is-llvm/binutils")
            appendLine("    # is added here because maturin-based packages such as jiter may need")
            appendLine("    # LLVM binutils while building native Android wheels.")
            appendLine("    pkg install -y python clang rust make pkg-config libffi openssl ca-certificates curl 2>&1 | tee -a \"\$HOME/.hermes/logs/install.log\" || true")
            appendLine("    pkg install -y binutils-is-llvm 2>&1 | tee -a \"\$HOME/.hermes/logs/install.log\" || pkg install -y binutils 2>&1 | tee -a \"\$HOME/.hermes/logs/install.log\" || true")
            appendLine("    prepare_android_rust_env")
            appendLine("}")
            appendLine()
            appendLine("prepare_android_rust_env")
            appendLine()
            appendLine("# Get stage manifest (Fix S2F02: use --manifest)")
            appendLine("MANIFEST=\$(bash \"\$HOME/hermes_install.sh\" --manifest 2>/dev/null || true)")
            appendLine("if [ -z \"\$MANIFEST\" ]; then")
            appendLine("    # Fallback: run install.sh directly if manifest fails. Keep this")
            appendLine("    # non-interactive so the Android app never blocks on a shell prompt.")
            appendLine("    STAGE=\"prerequisites\"")
            appendLine("    report_progress \"\$STAGE\" \"Running install.sh...\" 10")
            appendLine("    bash \"\$HOME/hermes_install.sh\" --skip-setup 2>&1 | tee -a \"\$HOME/.hermes/logs/install.log\"")
            appendLine("else")
            appendLine("    # Parse the manifest instead of hard-coding stages. Upstream owns the")
            appendLine("    # stage list; this app only drives the documented protocol.")
            appendLine("    STAGES=\$(printf '%s' \"\$MANIFEST\" | python3 -c \"import sys,json; print('\\n'.join(s['name'] for s in json.loads(sys.stdin.read())['stages']))\" 2>/dev/null || true)")
            appendLine("    if [ -z \"\$STAGES\" ]; then")
            appendLine("        STAGES=\$(printf '%s\\n' prerequisites repository venv python-deps node-deps path config setup gateway complete)")
            appendLine("    fi")
            appendLine("    STAGE_COUNT=\$(printf '%s\\n' \"\$STAGES\" | sed '/^$/d' | wc -l | tr -d ' ')")
            appendLine("    if [ -z \"\$STAGE_COUNT\" ] || [ \"\$STAGE_COUNT\" -le 0 ]; then STAGE_COUNT=10; fi")
            appendLine("    CURRENT=0")
            appendLine("    while IFS= read -r STAGE; do")
            appendLine("        [ -z \"\$STAGE\" ] && continue")
            appendLine("        CURRENT=\$((CURRENT + 1))")
            appendLine("        PERCENT=\$((CURRENT * 88 / STAGE_COUNT))")
            appendLine("        report_progress \"\$STAGE\" \"Running stage: \$STAGE\" \$PERCENT")
            appendLine("        if [ \"\$STAGE\" = \"python-deps\" ]; then")
            appendLine("            ensure_termux_rust_build_prereqs")
            appendLine("        fi")
            appendLine("        # Run stage with --json output (Fix S2F02). --non-interactive lets")
            appendLine("        # upstream skip setup/gateway prompt stages cleanly.")
            appendLine("        if STAGE_RESULT=\$(bash \"\$HOME/hermes_install.sh\" --stage \"\$STAGE\" --json --non-interactive 2>&1 | tee -a \"\$HOME/.hermes/logs/install.log\"); then")
            appendLine("            continue")
            appendLine("        fi")
            appendLine("        if [ \"\$STAGE\" = \"python-deps\" ] && printf '%s\\n' \"\$STAGE_RESULT\" | grep -qi \"platform android is not supported\"; then")
            appendLine("            report_progress \"\$STAGE\" \"Retrying psutil Android shim inside the Hermes venv...\" \$PERCENT")
            appendLine("            PIP_PYTHON=\"\$REPO_DIR/venv/bin/python\"")
            appendLine("            [ -x \"\$PIP_PYTHON\" ] || PIP_PYTHON=\"\$(command -v python3)\"")
            appendLine("            if [ -f \"\$REPO_DIR/scripts/install_psutil_android.py\" ]; then")
            appendLine("                \"\$PIP_PYTHON\" \"\$REPO_DIR/scripts/install_psutil_android.py\" --pip \"\$PIP_PYTHON -m pip\" 2>&1 | tee -a \"\$HOME/.hermes/logs/install.log\" || true")
            appendLine("            fi")
            appendLine("            if STAGE_RESULT=\$(bash \"\$HOME/hermes_install.sh\" --stage \"\$STAGE\" --json --non-interactive 2>&1 | tee -a \"\$HOME/.hermes/logs/install.log\"); then")
            appendLine("                continue")
            appendLine("            fi")
            appendLine("        fi")
            appendLine("        if [ \"\$STAGE\" = \"complete\" ] && command -v hermes >/dev/null 2>&1; then")
            appendLine("            report_progress \"\$STAGE\" \"Hermes installed successfully (ignoring complete stage warning)\" \$PERCENT")
            appendLine("            continue")
            appendLine("        fi")
            appendLine("        report_error \"Stage \$STAGE failed: \$STAGE_RESULT\"")
            appendLine("        exit 1")
            appendLine("    done <<EOF")
            appendLine("\$STAGES")
            appendLine("EOF")
            appendLine("fi")
            appendLine()
            appendLine("# The Android app talks to `hermes dashboard` /api/ws. If upstream fell")
            appendLine("# back from .[termux-all] to .[termux], make sure the web extra exists.")
            appendLine("STAGE=\"dashboard_deps\"")
            appendLine("report_progress \"\$STAGE\" \"Checking dashboard WebSocket dependencies...\" 90")
            appendLine("DASHBOARD_PY=\"\$REPO_DIR/venv/bin/python\"")
            appendLine("[ -x \"\$DASHBOARD_PY\" ] || DASHBOARD_PY=\"\$(command -v python3)\"")
            appendLine("if [ -d \"\$REPO_DIR\" ] && ! \"\$DASHBOARD_PY\" -c \"import fastapi, uvicorn, starlette\" >/dev/null 2>&1; then")
            appendLine("    report_progress \"\$STAGE\" \"Installing Hermes dashboard web extra...\" 90")
            appendLine("    (cd \"\$REPO_DIR\" && \"\$DASHBOARD_PY\" -m pip install -e '.[web]' -c constraints-termux.txt) 2>&1 | tee -a \"\$HOME/.hermes/logs/install.log\"")
            appendLine("fi")
            appendLine()
            appendLine("# Verify: hermes --version (Fix S2F05)")
            appendLine("STAGE=\"verify_version\"")
            appendLine("report_progress \"\$STAGE\" \"Checking hermes --version...\" 92")
            appendLine("export PATH=/data/data/com.termux/files/usr/bin:\$HOME/.hermes/hermes-agent/venv/bin:\$HOME/.hermes/venv/bin:\$HOME/.venv/bin:\$HOME/.local/bin:\$PATH")
            appendLine("HERMES_CMD=\"/data/data/com.termux/files/usr/bin/hermes\"")
            appendLine("if [ -f \"\$HOME/.hermes/hermes-agent/venv/bin/hermes\" ]; then")
            appendLine("    HERMES_CMD=\"\$HOME/.hermes/hermes-agent/venv/bin/hermes\"")
            appendLine("elif [ -f \"\$HOME/.hermes/venv/bin/hermes\" ]; then")
            appendLine("    HERMES_CMD=\"\$HOME/.hermes/venv/bin/hermes\"")
            appendLine("elif [ -f \"\$HOME/.venv/bin/hermes\" ]; then")
            appendLine("    HERMES_CMD=\"\$HOME/.venv/bin/hermes\"")
            appendLine("elif [ -f \"\$HOME/.local/bin/hermes\" ]; then")
            appendLine("    HERMES_CMD=\"\$HOME/.local/bin/hermes\"")
            appendLine("elif ! [ -f \"\$HERMES_CMD\" ] && command -v hermes >/dev/null 2>&1; then")
            appendLine("    HERMES_CMD=\"\$(command -v hermes)\"")
            appendLine("fi")
            appendLine("if ! [ -x \"\$HERMES_CMD\" ]; then")
            appendLine("    report_error \"Hermes command not found after install. Expected \$HERMES_CMD. Check \$HOME/.hermes/logs/install.log\"")
            appendLine("    exit 1")
            appendLine("fi")
            appendLine("HERMES_VERSION=\$(\"\$HERMES_CMD\" --version 2>&1)")
            appendLine("am broadcast -p \"\$RECEIVER\" -a \"\$PROGRESS_ACTION\" \\")
            appendLine("    --es stage \"verify_version\" \\")
            appendLine("    --es message \"Hermes version: \$HERMES_VERSION\" \\")
            appendLine("    --ei percent 94 >/dev/null 2>&1 || true")
            appendLine()
            appendLine("# Verify: hermes doctor (Fix S2F06)")
            appendLine("STAGE=\"verify_doctor\"")
            appendLine("report_progress \"\$STAGE\" \"Running hermes doctor...\" 96")
            appendLine("DOCTOR_OUTPUT=\$(\"\$HERMES_CMD\" doctor 2>&1 || echo \"doctor ready\")")
            appendLine("am broadcast -p \"\$RECEIVER\" -a \"\$PROGRESS_ACTION\" \\")
            appendLine("    --es stage \"verify_doctor\" \\")
            appendLine("    --es message \"Doctor: \$DOCTOR_OUTPUT\" \\")
            appendLine("    --ei percent 98 >/dev/null 2>&1 || true")
            appendLine()
            appendLine("# Detect Python version (Fix S2F01)")
            appendLine("PYTHON_VERSION=\$(python3 --version 2>&1 || echo \"unknown\")")
            appendLine("am broadcast -p \"\$RECEIVER\" -a \"\$PROGRESS_ACTION\" \\")
            appendLine("    --es stage \"python_version\" \\")
            appendLine("    --es message \"Python: \$PYTHON_VERSION\" \\")
            appendLine("    --ei percent 99 >/dev/null 2>&1 || true")
            appendLine()
            appendLine("STAGE=\"complete\"")
            appendLine("report_progress \"\$STAGE\" \"Installation complete! Hermes: \$HERMES_VERSION, Python: \$PYTHON_VERSION\" 100")
            appendLine("report_complete")
        }
    }

    /**
     * Legacy entry point preserved for the fallback "copy/paste" instructions
     * screen. The automated path uses [generateInstallScript] instead.
     */
    fun generateInstallCommand(): String = generateInstallScript()

    fun getScriptFilePath(): java.io.File? = null
}
